# Generated by Django 5.2.1 on 2026-03-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eather', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, default='Present', max_length=10, null=True),
        ),
    ]
