# docker-compose.prod.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  static_volume:
  media_volume:
